-- ==========================================
-- @description FV TrackFlow - Database Editor
-- @author frioventus
-- @version 0.8.1
-- @category Utility
-- The Database Management & Scanning Tool
-- ==========================================
if not reaper.ImGui_CreateContext then
  reaper.MB("Please install ReaImGui via ReaPack.", "Error", 0)
  return
end

local ctx = reaper.ImGui_CreateContext('FV TrackFlow Editor')
local script_path = debug.getinfo(1, "S").source:match("@?(.*[\\/])")
local db_filepath = script_path .. "database.lua"
local tags_filepath = script_path .. "tags_config.lua"

local scan_path = reaper.GetResourcePath() .. "/TrackTemplates"
local db_items = {}
local search_text = ""
local last_search_text = ""

local save_status_msg = ""
local save_status_time = 0

local cached_tree = { children = {}, folders = {} }
local needs_update = true

local tag_configs = {}
local sorted_unique_tags = {}
local clip_tags = ""
local clip_sends = {}
local clip_target = ""
local clip_mode = "NONE" 

local folder_to_rename, new_folder_name, show_rename_modal = nil, "", false
local item_to_delete, show_delete_modal = nil, false
local editing_item, show_edit_modal = nil, false
local new_empty_folder_name, show_new_folder_modal = "", false
local show_tag_modal = false

local pending_move = nil

local function NormalizePath(p)
    if not p then return "" end
    return string.lower(string.gsub(p, "\\", "/"))
end

local function GetFileName(path)
    if not path or path == "" then return "" end
    return path:match("([^/\\]+)$") or path
end

local function SplitString(inputstr, sep)
    if sep == nil then sep = "%s" end
    local t = {}
    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
        str = str:match("^%s*(.-)%s*$")
        if str ~= "" then table.insert(t, str) end
    end
    return t
end

if reaper.file_exists(db_filepath) then
    local loaded_data = dofile(db_filepath)
    for _, item in ipairs(loaded_data) do
        item.tree_path_str = item.tree_path and table.concat(item.tree_path, " / ") or ""
        item.tags_str = item.tags and table.concat(item.tags, ", ") or ""
        item.target_folder = item.target_folder or ""
        item.sends = (item.routing and item.routing.sends) and item.routing.sends or {}
        table.insert(db_items, item)
    end
end

if reaper.file_exists(tags_filepath) then
    local ok, t = pcall(dofile, tags_filepath)
    if ok and type(t) == "table" then tag_configs = t end
end

local function SaveDatabase()
    local file = io.open(db_filepath, "w")
    if not file then return false end
    file:write("-- Auto-generated by FV_TrackFlow_Editor\nreturn {\n")
    for _, item in ipairs(db_items) do
        file:write("  {\n")
        file:write("    id = \"" .. item.id .. "\",\n")
        file:write("    display_name = \"" .. item.display_name .. "\",\n")
        local safe_path = string.gsub(item.file_path, "\\", "/")
        file:write("    file_path = \"" .. safe_path .. "\",\n")
        file:write("    target_folder = \"" .. (item.target_folder or "") .. "\",\n")
        
        file:write("    tree_path = {")
        if item.tree_path_str ~= "" then
            local t_path = SplitString(item.tree_path_str, "/")
            for i, p in ipairs(t_path) do file:write("\"" .. p .. "\"" .. (i < #t_path and ", " or "")) end
        end
        file:write("},\n    tags = {")
        
        local t_tags = SplitString(item.tags_str, ",")
        for i, t in ipairs(t_tags) do file:write("\"" .. string.upper(t) .. "\"" .. (i < #t_tags and ", " or "")) end
        file:write("},\n    routing = {\n      sends = {\n")
        
        for _, send in ipairs(item.sends) do
            if send.target and send.target ~= "" then
                file:write("        { target = \"" .. send.target .. "\", level_db = " .. tostring(send.level_db) .. " },\n")
            end
        end
        file:write("      }\n    }\n  },\n")
    end
    file:write("}\n")
    file:close()
    return true
end

local function SaveTags()
    local f = io.open(tags_filepath, "w")
    if f then
        f:write("-- Auto-generated tag configurations\nreturn {\n")
        for tag, data in pairs(tag_configs) do
            f:write(string.format("  [\"%s\"] = { short = \"%s\", color = 0x%08X },\n", tag, data.short, data.color & 0xFFFFFFFF))
        end
        f:write("}\n")
        f:close()
    end
end

local function DrawMicroBadge(tag)
    local t_upper = string.upper(tag)
    local cfg = tag_configs[t_upper] or { short = string.sub(t_upper, 1, 3), color = 0x9E9E9EFF }
    
    reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(), cfg.color)
    reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_ButtonHovered(), cfg.color)
    reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_ButtonActive(), cfg.color)
    reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Text(), 0x111111FF)
    reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_FrameRounding(), 3)
    reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_FramePadding(), 5, 0)
    
    reaper.ImGui_Button(ctx, cfg.short)
    
    reaper.ImGui_PopStyleVar(ctx, 2)
    reaper.ImGui_PopStyleColor(ctx, 4)
end

-- ==========================================
-- AĞAÇ SİSTEMİ (Folders + Items Mixed)
-- ==========================================
local function UpdateEditorCache()
    cached_tree = { children = {}, folders = {} }
    local srch = search_text:lower()
    for _, item in ipairs(db_items) do
        local show_item = true
        if srch ~= "" then
            if not string.find(string.lower(item.display_name), srch) and not string.find(string.lower(item.tree_path_str), srch) then show_item = false end
        end
        if show_item then
            local parts = {}
            if item.tree_path_str and item.tree_path_str ~= "" then
                parts = SplitString(item.tree_path_str, "/")
            end
            
            local current_node = cached_tree
            for _, part in ipairs(parts) do
                part = part:match("^%s*(.-)%s*$")
                if not current_node.folders[part] then
                    local new_fld = { children = {}, folders = {}, name = part }
                    current_node.folders[part] = new_fld
                    table.insert(current_node.children, { type = "folder", name = part, node = new_fld })
                end
                current_node = current_node.folders[part]
            end
            table.insert(current_node.children, { type = "item", item = item })
        end
    end
end

local function RebuildDBFromTree()
    local new_db = {}
    local function Flatten(node, current_path)
        for _, child in ipairs(node.children) do
            if child.type == "item" then
                child.item.tree_path_str = current_path
                table.insert(new_db, child.item)
            elseif child.type == "folder" then
                local next_path = current_path == "" and child.name or (current_path .. "/" .. child.name)
                Flatten(child.node, next_path)
            end
        end
    end
    Flatten(cached_tree, "")
    db_items = new_db
    needs_update = true
end

local function RemoveNode(node, p_type, p_id, current_path)
    for i, child in ipairs(node.children) do
        if child.type == "item" and p_type == "ITEM" and child.item.id == p_id then
            return table.remove(node.children, i), i, node
        elseif child.type == "folder" and p_type == "FOLDER" then
            local f_path = current_path == "" and child.name or (current_path .. "/" .. child.name)
            if f_path == p_id then return table.remove(node.children, i), i, node end
        end
    end
    for _, child in ipairs(node.children) do
        if child.type == "folder" then
            local f_path = current_path == "" and child.name or (current_path .. "/" .. child.name)
            local obj, idx, p_node = RemoveNode(child.node, p_type, p_id, f_path)
            if obj then return obj, idx, p_node end
        end
    end
    return nil, nil, nil
end

local function GetNodeByPath(node, path)
    if path == "" then return node end
    local parts = SplitString(path, "/")
    local current = node
    for _, part in ipairs(parts) do
        part = part:match("^%s*(.-)%s*$")
        if current.folders[part] then current = current.folders[part]
        else return nil end
    end
    return current
end

-- ==========================================
-- RECURSIVE ÇİZİCİ
-- ==========================================
local function DrawNodeContent(node, parent_path, parent_node)
    for idx, child in ipairs(node.children) do
        
        if child.type == "folder" then
            local folder_name = child.name
            local full_path = parent_path == "" and folder_name or (parent_path .. "/" .. folder_name)
            
            reaper.ImGui_PushID(ctx, "fld_" .. full_path)
            reaper.ImGui_TableNextRow(ctx)
            if search_text ~= "" then reaper.ImGui_SetNextItemOpen(ctx, true, reaper.ImGui_Cond_Always()) end
            
            reaper.ImGui_TableSetColumnIndex(ctx, 0)
            
            local function count_items(n)
                local c = 0
                for _, ch in ipairs(n.children) do
                    if ch.type == "item" then c = c + 1 else c = c + count_items(ch.node) end
                end
                return c
            end
            
            local label = folder_name .. " (" .. count_items(child.node) .. " items)"
            local node_open = reaper.ImGui_TreeNode(ctx, label .. "###tree_" .. full_path)
            
            if search_text == "" and reaper.ImGui_BeginDragDropSource(ctx) then
                reaper.ImGui_SetDragDropPayload(ctx, 'DND_OBJ', "FOLDER|" .. full_path)
                reaper.ImGui_Text(ctx, "Moving Folder: " .. folder_name)
                reaper.ImGui_EndDragDropSource(ctx)
            end
            
            if search_text == "" and reaper.ImGui_BeginDragDropTarget(ctx) then
                local rv, payload_str = reaper.ImGui_AcceptDragDropPayload(ctx, 'DND_OBJ')
                if rv and payload_str then
                    local src_type, src_id = payload_str:match("^(%w+)|(.*)$")
                    if src_type == "ITEM" or (src_type == "FOLDER" and src_id ~= full_path) then
                        pending_move = { src_type = src_type, src_id = src_id, dst_parent = full_path }
                    end
                end
                reaper.ImGui_EndDragDropTarget(ctx)
            end
            
            if reaper.ImGui_BeginPopupContextItem(ctx, "ctx_fld_" .. full_path) then
                if search_text == "" and parent_node then
                    if idx > 1 then
                        if reaper.ImGui_MenuItem(ctx, "Move Up (Sort)") then
                            parent_node.children[idx], parent_node.children[idx-1] = parent_node.children[idx-1], parent_node.children[idx]
                            RebuildDBFromTree(); UpdateEditorCache()
                        end
                    end
                    if idx < #parent_node.children then
                        if reaper.ImGui_MenuItem(ctx, "Move Down (Sort)") then
                            parent_node.children[idx], parent_node.children[idx+1] = parent_node.children[idx+1], parent_node.children[idx]
                            RebuildDBFromTree(); UpdateEditorCache()
                        end
                    end
                    reaper.ImGui_Separator(ctx)
                end
                if reaper.ImGui_MenuItem(ctx, "Rename Folder...") then folder_to_rename = full_path; new_folder_name = full_path; show_rename_modal = true end
                if reaper.ImGui_MenuItem(ctx, "Create New Folder Here...") then new_empty_folder_name = full_path .. "/New Folder"; show_new_folder_modal = true end
                reaper.ImGui_EndPopup(ctx)
            end
            
            if node_open then
                DrawNodeContent(child.node, full_path, node)
                reaper.ImGui_TreePop(ctx)
            end
            reaper.ImGui_PopID(ctx)
            
        elseif child.type == "item" then
            local item = child.item
            reaper.ImGui_PushID(ctx, "itm_" .. item.id)
            reaper.ImGui_TableNextRow(ctx)
            
            reaper.ImGui_TableSetColumnIndex(ctx, 0)
            reaper.ImGui_Indent(ctx, 8) 
            
            local start_pos_x = reaper.ImGui_GetCursorPosX(ctx)
            local start_pos_y = reaper.ImGui_GetCursorPosY(ctx)
            
            reaper.ImGui_Selectable(ctx, "##sel_"..item.id, false, reaper.ImGui_SelectableFlags_SpanAllColumns())
            
            local end_pos_y = reaper.ImGui_GetCursorPosY(ctx)
            
            if reaper.ImGui_IsItemHovered(ctx) then
                if reaper.ImGui_IsKeyPressed(ctx, reaper.ImGui_Key_Delete()) then
                    item_to_delete = item; show_delete_modal = true
                end
            end
            
            if search_text == "" and reaper.ImGui_BeginDragDropSource(ctx) then
                reaper.ImGui_SetDragDropPayload(ctx, 'DND_OBJ', "ITEM|" .. item.id)
                reaper.ImGui_Text(ctx, "Moving Track: " .. item.display_name)
                reaper.ImGui_EndDragDropSource(ctx)
            end
            
            if reaper.ImGui_BeginPopupContextItem(ctx, "ctx_itm_" .. item.id) then
                if search_text == "" and parent_node then
                    if idx > 1 then
                        if reaper.ImGui_MenuItem(ctx, "Move Up (Sort)") then
                            parent_node.children[idx], parent_node.children[idx-1] = parent_node.children[idx-1], parent_node.children[idx]
                            RebuildDBFromTree(); UpdateEditorCache()
                        end
                    end
                    if idx < #parent_node.children then
                        if reaper.ImGui_MenuItem(ctx, "Move Down (Sort)") then
                            parent_node.children[idx], parent_node.children[idx+1] = parent_node.children[idx+1], parent_node.children[idx]
                            RebuildDBFromTree(); UpdateEditorCache()
                        end
                    end
                    reaper.ImGui_Separator(ctx)
                end
                
                if reaper.ImGui_MenuItem(ctx, "Edit Settings...") then editing_item = item; show_edit_modal = true end
                reaper.ImGui_Separator(ctx)
                if reaper.ImGui_MenuItem(ctx, "Copy Target Folder") then clip_target = item.target_folder or ""; clip_mode = "TARGET" end
                if reaper.ImGui_MenuItem(ctx, "Copy Tags") then clip_tags = item.tags_str; clip_mode = "TAGS" end
                if reaper.ImGui_MenuItem(ctx, "Copy Sends") then 
                    clip_sends = {}; for _, s in ipairs(item.sends) do table.insert(clip_sends, {target = s.target, level_db = s.level_db}) end
                    clip_mode = "SENDS" 
                end
                if reaper.ImGui_MenuItem(ctx, "Copy ALL Data") then 
                    clip_tags = item.tags_str; clip_target = item.target_folder or ""
                    clip_sends = {}; for _, s in ipairs(item.sends) do table.insert(clip_sends, {target = s.target, level_db = s.level_db}) end
                    clip_mode = "ALL" 
                end
                local paste_label = "Paste Data " .. (clip_mode ~= "NONE" and "(" .. clip_mode .. ")" or "")
                if reaper.ImGui_MenuItem(ctx, paste_label, nil, false, clip_mode ~= "NONE") then
                    if clip_mode == "TARGET" or clip_mode == "ALL" then item.target_folder = clip_target end
                    if clip_mode == "TAGS" or clip_mode == "ALL" then item.tags_str = clip_tags end
                    if clip_mode == "SENDS" or clip_mode == "ALL" then
                        item.sends = {}
                        for _, s in ipairs(clip_sends) do table.insert(item.sends, {target = s.target, level_db = s.level_db}) end
                    end
                    needs_update = true
                end
                reaper.ImGui_Separator(ctx)
                reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Text(), 0xEF5350FF)
                if reaper.ImGui_MenuItem(ctx, "Delete Template... (Del)") then item_to_delete = item; show_delete_modal = true end
                reaper.ImGui_PopStyleColor(ctx)
                reaper.ImGui_EndPopup(ctx)
            end

            reaper.ImGui_SetCursorPos(ctx, start_pos_x, start_pos_y)
            reaper.ImGui_Text(ctx, item.display_name)
            if item.target_folder and item.target_folder ~= "" then
                reaper.ImGui_SameLine(ctx)
                reaper.ImGui_TextColored(ctx, 0xFFB74DFF, "[ → " .. item.target_folder .. " ]")
            end
            
            reaper.ImGui_SetCursorPosY(ctx, end_pos_y)
            reaper.ImGui_Dummy(ctx, 0, 0)
            reaper.ImGui_Unindent(ctx, 8)
            
            reaper.ImGui_TableSetColumnIndex(ctx, 1)
            reaper.ImGui_TextDisabled(ctx, item.tree_path_str)
            
            reaper.ImGui_TableSetColumnIndex(ctx, 2)
            if item.tags_str == "" then reaper.ImGui_TextDisabled(ctx, "-")
            else
                local t_list = SplitString(item.tags_str, ",")
                for t_idx, t in ipairs(t_list) do
                    DrawMicroBadge(t)
                    if t_idx < #t_list then reaper.ImGui_SameLine(ctx, 0, 4) end
                end
            end
            
            reaper.ImGui_TableSetColumnIndex(ctx, 3)
            local send_summary = "-"
            if #item.sends > 0 then
                local temp_sends = {}
                for _, s in ipairs(item.sends) do table.insert(temp_sends, s.target) end
                send_summary = table.concat(temp_sends, ", ")
            end
            reaper.ImGui_TextDisabled(ctx, send_summary)
            reaper.ImGui_PopID(ctx)
        end
    end
end

-- ==========================================
-- SCANNER FONKSİYONLARI 
-- ==========================================
local function AddSingleFile()
    local retval, filename = reaper.GetUserFileNameForRead(scan_path, "Select Track Template", "*.RTrackTemplate")
    if retval then
        local new_file_name = string.lower(GetFileName(filename))
        local exists = false
        for _, item in ipairs(db_items) do
            if string.lower(GetFileName(item.file_path)) == new_file_name then exists = true break end
        end
        if not exists then
            local name_with_ext = filename:match("([^/\\]+)$")
            local name_no_ext = name_with_ext:gsub("%.RTrackTemplate$", "")
            table.insert(db_items, {
                id = "tpl_" .. tostring(math.random(100000, 999999)), file_path = filename, display_name = name_no_ext, 
                tree_path_str = "", target_folder = "", tags_str = "", sends = {}
            })
            needs_update = true
        end
    end
end

local function ScanDirectory(current_path, base_path)
    local i = 0
    while true do
        local file = reaper.EnumerateFiles(current_path, i)
        if not file then break end
        if string.match(file, "%.RTrackTemplate$") then
            local full_path = current_path .. "/" .. file
            local new_file_name = string.lower(GetFileName(full_path))
            local exists = false
            for _, item in ipairs(db_items) do
                if string.lower(GetFileName(item.file_path)) == new_file_name then exists = true break end
            end
            if not exists then
                local name_no_ext = string.gsub(file, "%.RTrackTemplate$", "")
                local relative_path = string.sub(current_path, string.len(base_path) + 2)
                local auto_tree_str = ""
                if relative_path and relative_path ~= "" then auto_tree_str = string.gsub(string.gsub(relative_path, "\\", "/"), "/", " / ") end
                table.insert(db_items, { id = "tpl_" .. tostring(math.random(100000, 999999)), file_path = full_path, display_name = name_no_ext, tree_path_str = auto_tree_str, target_folder = "", tags_str = "", sends = {} })
                needs_update = true
            end
        end
        i = i + 1
    end
    local j = 0
    while true do
        local subdir = reaper.EnumerateSubdirectories(current_path, j)
        if not subdir then break end
        ScanDirectory(current_path .. "/" .. subdir, base_path)
        j = j + 1
    end
end

local function loop()
    reaper.ImGui_SetNextWindowSize(ctx, 1000, 600, reaper.ImGui_Cond_FirstUseEver())
    local visible, open = reaper.ImGui_Begin(ctx, 'FV TrackFlow - Database Editor', true)
    
    if visible then
        if search_text ~= last_search_text or needs_update then
            UpdateEditorCache()
            last_search_text = search_text
            needs_update = false
        end

        reaper.ImGui_PushItemWidth(ctx, 250)
        local changed, new_path = reaper.ImGui_InputText(ctx, "##ScanPath", scan_path)
        if changed then scan_path = new_path end
        reaper.ImGui_PopItemWidth(ctx)
        
        reaper.ImGui_SameLine(ctx)
        if reaper.ImGui_Button(ctx, "BROWSE", 70) then
            if reaper.JS_Dialog_BrowseForFolder then
                local rv, folder = reaper.JS_Dialog_BrowseForFolder("Select Folder", scan_path)
                if rv == 1 and folder ~= "" then scan_path = folder end
            end
        end

        reaper.ImGui_SameLine(ctx)
        if reaper.ImGui_Button(ctx, "SCAN", 70) then ScanDirectory(scan_path, scan_path) end
        reaper.ImGui_SameLine(ctx)
        if reaper.ImGui_Button(ctx, "ADD FILE", 80) then AddSingleFile() end
        
        reaper.ImGui_SameLine(ctx)
        reaper.ImGui_Dummy(ctx, 20, 1)
        reaper.ImGui_SameLine(ctx)
        
        reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(), 0x8E24AAFF)
        reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_ButtonHovered(), 0xAB47BCFF)
        if reaper.ImGui_Button(ctx, "TAG MANAGER", 110) then 
            local unique = {}
            for _, item in ipairs(db_items) do
                local t_list = SplitString(item.tags_str, ",")
                for _, t in ipairs(t_list) do unique[string.upper(t)] = true end
            end
            sorted_unique_tags = {}
            for t in pairs(unique) do
                table.insert(sorted_unique_tags, t)
                if not tag_configs[t] then tag_configs[t] = { short = string.sub(t, 1, 3), color = 0x9E9E9EFF } end
            end
            table.sort(sorted_unique_tags)
            show_tag_modal = true 
        end
        reaper.ImGui_PopStyleColor(ctx, 2)
        
        reaper.ImGui_SameLine(ctx)
        reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(), 0x1E88E5FF)
        reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_ButtonHovered(), 0x42A5F5FF)
        if reaper.ImGui_Button(ctx, "SAVE SETTINGS", 120) then
            if SaveDatabase() then 
                save_status_msg = "Saved successfully!"
                save_status_time = reaper.time_precise() 
                -- MAGIC: Ana scripte "Güncellendi" sinyali gönder!
                reaper.SetExtState("FV_TrackFlow", "NeedsReload", "1", false)
            end
        end
        reaper.ImGui_PopStyleColor(ctx, 2)
        
        if (reaper.time_precise() - save_status_time) < 3.0 then
            reaper.ImGui_SameLine(ctx)
            reaper.ImGui_TextColored(ctx, 0x4CAF50FF, save_status_msg)
        end
        
        reaper.ImGui_Spacing(ctx); reaper.ImGui_Separator(ctx); reaper.ImGui_Spacing(ctx)

        reaper.ImGui_PushItemWidth(ctx, 300)
        local s_changed, n_search = reaper.ImGui_InputTextWithHint(ctx, "##SearchDB", "Search library...", search_text)
        if s_changed then search_text = n_search end
        reaper.ImGui_PopItemWidth(ctx)
        
        reaper.ImGui_SameLine(ctx)
        reaper.ImGui_TextDisabled(ctx, "(Tip: Drag & Drop into folders or Root. Right-Click to Sort, Edit or Delete)")
        
        reaper.ImGui_Spacing(ctx)

        local table_flags = reaper.ImGui_TableFlags_RowBg() | reaper.ImGui_TableFlags_BordersInnerH() | 
                            reaper.ImGui_TableFlags_ScrollY() | reaper.ImGui_TableFlags_Resizable() |
                            reaper.ImGui_TableFlags_BordersOuter()
        
        reaper.ImGui_PushStyleVar(ctx, reaper.ImGui_StyleVar_IndentSpacing(), 12)
        reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_HeaderHovered(), 0xFFFFFF15) 
        reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_HeaderActive(), 0xFFFFFF25)  
        
        if reaper.ImGui_BeginTable(ctx, "DBTable", 4, table_flags) then
            reaper.ImGui_TableSetupScrollFreeze(ctx, 0, 1)
            reaper.ImGui_TableSetupColumn(ctx, "Track Name (Folders)", reaper.ImGui_TableColumnFlags_WidthStretch(), 2.0)
            reaper.ImGui_TableSetupColumn(ctx, "Folder Path", reaper.ImGui_TableColumnFlags_WidthStretch(), 2.5)
            reaper.ImGui_TableSetupColumn(ctx, "Tags", reaper.ImGui_TableColumnFlags_WidthStretch(), 1.5)
            reaper.ImGui_TableSetupColumn(ctx, "Sends", reaper.ImGui_TableColumnFlags_WidthStretch(), 1.0)
            reaper.ImGui_TableHeadersRow(ctx)
            
            -- ROOT (ANA DİZİN) HEDEF ALANI
            if search_text == "" then
                reaper.ImGui_TableNextRow(ctx)
                reaper.ImGui_TableSetColumnIndex(ctx, 0)
                reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Text(), 0x888888FF)
                reaper.ImGui_Selectable(ctx, "  [ + Root Directory ]", false, reaper.ImGui_SelectableFlags_SpanAllColumns())
                reaper.ImGui_PopStyleColor(ctx)
                
                if reaper.ImGui_BeginDragDropTarget(ctx) then
                    local rv, payload_str = reaper.ImGui_AcceptDragDropPayload(ctx, 'DND_OBJ')
                    if rv and payload_str then
                        local src_type, src_id = payload_str:match("^(%w+)|(.*)$")
                        pending_move = { src_type = src_type, src_id = src_id, dst_parent = "" }
                    end
                    reaper.ImGui_EndDragDropTarget(ctx)
                end
            end

            DrawNodeContent(cached_tree, "", cached_tree)
            
            reaper.ImGui_EndTable(ctx)
        end
        
        reaper.ImGui_PopStyleColor(ctx, 2)
        reaper.ImGui_PopStyleVar(ctx)
        
        if pending_move then
            local safe = true
            if pending_move.src_type == "FOLDER" then
                if pending_move.dst_parent == pending_move.src_id or
                   string.sub(pending_move.dst_parent, 1, #pending_move.src_id + 1) == pending_move.src_id .. "/" then
                   safe = false
                end
            end
            
            if safe then
                local moved_obj, _, _ = RemoveNode(cached_tree, pending_move.src_type, pending_move.src_id, "")
                if moved_obj then
                    local target_parent_node = GetNodeByPath(cached_tree, pending_move.dst_parent) or cached_tree
                    table.insert(target_parent_node.children, moved_obj)
                end
            end
            
            RebuildDBFromTree()
            UpdateEditorCache()
            pending_move = nil
        end
        
        if show_tag_modal then reaper.ImGui_OpenPopup(ctx, "Tag Color & Name Manager"); show_tag_modal = false end
        reaper.ImGui_SetNextWindowSizeConstraints(ctx, 350, 200, 350, 500)
        if reaper.ImGui_BeginPopupModal(ctx, "Tag Color & Name Manager", nil, reaper.ImGui_WindowFlags_AlwaysAutoResize()) then
            reaper.ImGui_TextDisabled(ctx, "Set custom colors and short names for tags.")
            reaper.ImGui_Spacing(ctx); reaper.ImGui_Separator(ctx); reaper.ImGui_Spacing(ctx)
            
            reaper.ImGui_BeginChild(ctx, "TagsScroll", 0, 300, 0)
            for _, tag in ipairs(sorted_unique_tags) do
                reaper.ImGui_AlignTextToFramePadding(ctx)
                reaper.ImGui_Text(ctx, tag)
                
                reaper.ImGui_SameLine(ctx, 130)
                reaper.ImGui_PushID(ctx, "sh_"..tag)
                reaper.ImGui_PushItemWidth(ctx, 60)
                local rv_s, ns = reaper.ImGui_InputText(ctx, "##short", tag_configs[tag].short)
                if rv_s then tag_configs[tag].short = string.sub(ns, 1, 4) end
                reaper.ImGui_PopItemWidth(ctx)
                reaper.ImGui_PopID(ctx)
                
                reaper.ImGui_SameLine(ctx, 200)
                reaper.ImGui_PushID(ctx, "col_"..tag)
                local c_flags = reaper.ImGui_ColorEditFlags_NoInputs() | reaper.ImGui_ColorEditFlags_AlphaBar()
                local rv_c, nc = reaper.ImGui_ColorEdit4(ctx, "Color", tag_configs[tag].color, c_flags)
                if rv_c then tag_configs[tag].color = nc end
                reaper.ImGui_PopID(ctx)
            end
            reaper.ImGui_EndChild(ctx)
            
            reaper.ImGui_Spacing(ctx); reaper.ImGui_Separator(ctx); reaper.ImGui_Spacing(ctx)
            if reaper.ImGui_Button(ctx, "Save & Close", 120) then
                SaveTags()
                needs_update = true
                reaper.ImGui_CloseCurrentPopup(ctx)
            end
            reaper.ImGui_SameLine(ctx)
            if reaper.ImGui_Button(ctx, "Cancel", 100) then reaper.ImGui_CloseCurrentPopup(ctx) end
            reaper.ImGui_EndPopup(ctx)
        end
        
        if show_rename_modal and folder_to_rename then
            reaper.ImGui_OpenPopup(ctx, "Rename Folder")
            show_rename_modal = false
        end
        if reaper.ImGui_BeginPopupModal(ctx, "Rename Folder", nil, reaper.ImGui_WindowFlags_AlwaysAutoResize()) then
            reaper.ImGui_Text(ctx, "Rename all items in folder:\n[" .. folder_to_rename .. "]")
            reaper.ImGui_Spacing(ctx)
            reaper.ImGui_PushItemWidth(ctx, 350)
            local rv, text = reaper.ImGui_InputText(ctx, "##newfldname", new_folder_name)
            if rv then new_folder_name = text end
            reaper.ImGui_PopItemWidth(ctx)
            reaper.ImGui_Spacing(ctx); reaper.ImGui_Separator(ctx); reaper.ImGui_Spacing(ctx)
            if reaper.ImGui_Button(ctx, "Save & Apply", 150) then
                for _, item in ipairs(db_items) do
                    if item.tree_path_str == folder_to_rename then
                        item.tree_path_str = new_folder_name
                    elseif string.sub(item.tree_path_str, 1, string.len(folder_to_rename) + 1) == folder_to_rename .. "/" then
                        item.tree_path_str = new_folder_name .. string.sub(item.tree_path_str, string.len(folder_to_rename) + 1)
                    end
                end
                needs_update = true
                reaper.ImGui_CloseCurrentPopup(ctx)
            end
            reaper.ImGui_SameLine(ctx)
            if reaper.ImGui_Button(ctx, "Cancel", 100) then reaper.ImGui_CloseCurrentPopup(ctx) end
            reaper.ImGui_EndPopup(ctx)
        end
        
        if show_new_folder_modal then
            reaper.ImGui_OpenPopup(ctx, "Create New Folder")
            show_new_folder_modal = false
        end
        if reaper.ImGui_BeginPopupModal(ctx, "Create New Folder", nil, reaper.ImGui_WindowFlags_AlwaysAutoResize()) then
            reaper.ImGui_Text(ctx, "Enter new folder path (Use '/' for subfolders):")
            reaper.ImGui_Spacing(ctx)
            reaper.ImGui_PushItemWidth(ctx, 350)
            local rv, text = reaper.ImGui_InputText(ctx, "##createfldname", new_empty_folder_name)
            if rv then new_empty_folder_name = text end
            reaper.ImGui_PopItemWidth(ctx)
            reaper.ImGui_Spacing(ctx); reaper.ImGui_Separator(ctx); reaper.ImGui_Spacing(ctx)
            if reaper.ImGui_Button(ctx, "Create", 100) then
                table.insert(db_items, { id = "dir_" .. tostring(math.random(100000, 999999)), file_path = "", display_name = "(Empty Folder)", tree_path_str = new_empty_folder_name, target_folder = "", tags_str = "", sends = {} })
                needs_update = true
                reaper.ImGui_CloseCurrentPopup(ctx)
            end
            reaper.ImGui_SameLine(ctx)
            if reaper.ImGui_Button(ctx, "Cancel", 100) then reaper.ImGui_CloseCurrentPopup(ctx) end
            reaper.ImGui_EndPopup(ctx)
        end
        
        if show_edit_modal and editing_item then
            reaper.ImGui_OpenPopup(ctx, "Edit Track Template")
            show_edit_modal = false
        end
        reaper.ImGui_SetNextWindowSize(ctx, 450, 0, reaper.ImGui_Cond_Appearing())
        if reaper.ImGui_BeginPopupModal(ctx, "Edit Track Template", nil, reaper.ImGui_WindowFlags_NoSavedSettings()) then
            local item = editing_item
            reaper.ImGui_TextDisabled(ctx, "File: " .. (item.file_path == "" and "Virtual Folder" or item.file_path))
            reaper.ImGui_Spacing(ctx); reaper.ImGui_Separator(ctx); reaper.ImGui_Spacing(ctx)
            if item.file_path ~= "" then
                reaper.ImGui_PushItemWidth(ctx, -1)
                reaper.ImGui_Text(ctx, "Track Name:")
                local rv1, n_name = reaper.ImGui_InputText(ctx, "##m_name", item.display_name)
                if rv1 then item.display_name = n_name; needs_update = true end
            end
            
            reaper.ImGui_Spacing(ctx)
            reaper.ImGui_Text(ctx, "Folder Path (Separate with '/'):")
            local rv2, n_tree = reaper.ImGui_InputText(ctx, "##m_tree", item.tree_path_str)
            if rv2 then item.tree_path_str = n_tree; needs_update = true end
            
            if item.file_path ~= "" then
                reaper.ImGui_Spacing(ctx)
                reaper.ImGui_Text(ctx, "Auto-Insert Target Track (REAPER):")
                local rv_tgt, n_tgt = reaper.ImGui_InputText(ctx, "##m_target", item.target_folder or "")
                if rv_tgt then item.target_folder = n_tgt; needs_update = true end
                if reaper.ImGui_IsItemHovered(ctx) then reaper.ImGui_SetTooltip(ctx, "If this REAPER track exists, template will be inserted inside it automatically.") end
                
                reaper.ImGui_Spacing(ctx)
                reaper.ImGui_Text(ctx, "Tags (Separate with ','):")
                local rv3, n_tags = reaper.ImGui_InputText(ctx, "##m_tags", item.tags_str)
                if rv3 then item.tags_str = n_tags; needs_update = true end
                reaper.ImGui_PopItemWidth(ctx)
                
                reaper.ImGui_Spacing(ctx); reaper.ImGui_Separator(ctx); reaper.ImGui_Spacing(ctx)
                reaper.ImGui_Text(ctx, "FX SENDS:")
                reaper.ImGui_SameLine(ctx)
                if reaper.ImGui_Button(ctx, "+ Add Send") then table.insert(item.sends, {target = "", level_db = 0.0}); needs_update = true end
                local sends_to_remove = {}
                for s_idx, send in ipairs(item.sends) do
                    reaper.ImGui_PushID(ctx, "m_send_" .. s_idx)
                    reaper.ImGui_PushItemWidth(ctx, 150)
                    local rvt, nt = reaper.ImGui_InputText(ctx, "Target", send.target)
                    if rvt then send.target = nt; needs_update = true end
                    reaper.ImGui_PopItemWidth(ctx)
                    reaper.ImGui_SameLine(ctx)
                    reaper.ImGui_PushItemWidth(ctx, 80)
                    local rvl, nl = reaper.ImGui_InputDouble(ctx, "dB", send.level_db, 0.5, 1.0, "%.1f")
                    if rvl then send.level_db = nl; needs_update = true end
                    reaper.ImGui_PopItemWidth(ctx)
                    reaper.ImGui_SameLine(ctx)
                    if reaper.ImGui_Button(ctx, "X") then table.insert(sends_to_remove, s_idx) end
                    reaper.ImGui_PopID(ctx)
                end
                for r = #sends_to_remove, 1, -1 do table.remove(item.sends, sends_to_remove[r]); needs_update = true end
            end
            reaper.ImGui_Spacing(ctx); reaper.ImGui_Separator(ctx); reaper.ImGui_Spacing(ctx)
            if reaper.ImGui_Button(ctx, "Done", 100) then needs_update = true; reaper.ImGui_CloseCurrentPopup(ctx) end
            reaper.ImGui_EndPopup(ctx)
        end

        if show_delete_modal and item_to_delete then
            reaper.ImGui_OpenPopup(ctx, "Confirm Delete")
            show_delete_modal = false
        end
        if reaper.ImGui_BeginPopupModal(ctx, "Confirm Delete", nil, reaper.ImGui_WindowFlags_AlwaysAutoResize()) then
            local del_item = item_to_delete
            reaper.ImGui_Text(ctx, "Are you sure you want to permanently remove:\n\n'" .. (del_item and del_item.display_name or "Unknown") .. "'\n\nfrom the database?")
            reaper.ImGui_Spacing(ctx); reaper.ImGui_Separator(ctx); reaper.ImGui_Spacing(ctx)
            reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_Button(), 0xAA3333FF)
            reaper.ImGui_PushStyleColor(ctx, reaper.ImGui_Col_ButtonHovered(), 0xCC4444FF)
            if reaper.ImGui_Button(ctx, "Yes, Delete It", 150) then
                for j, it in ipairs(db_items) do
                    if it == del_item then table.remove(db_items, j) break end
                end
                needs_update = true
                item_to_delete = nil
                reaper.ImGui_CloseCurrentPopup(ctx)
            end
            reaper.ImGui_PopStyleColor(ctx, 2)
            reaper.ImGui_SameLine(ctx)
            if reaper.ImGui_Button(ctx, "Cancel", 100) then item_to_delete = nil; reaper.ImGui_CloseCurrentPopup(ctx) end
            reaper.ImGui_EndPopup(ctx)
        end

        reaper.ImGui_End(ctx)
    end
    
    if open then reaper.defer(loop) end
end

reaper.defer(loop)
