-- ==========================================
-- @description FV TrackFlow - Core Engine
-- @author frioventus
-- @version 0.8.0
-- @nomain
-- The Engine: Handles database, search logic, and Reaper API insertion.
-- ==========================================

local Core = {}
Core.track_templates = {}
Core.tag_configs = {}

function Core.Init(script_path)
    local db_file = script_path .. "database.lua"
    local tags_file = script_path .. "tags_config.lua"
    
    if reaper.file_exists(tags_file) then
        local ok, t = pcall(dofile, tags_file)
        if ok and type(t) == "table" then Core.tag_configs = t end
    end
    
    if reaper.file_exists(db_file) then
        Core.track_templates = dofile(db_file)
        return true
    end
    return false
end

function Core.SaveDatabase(script_path)
    local db_filepath = script_path .. "database.lua"
    local file = io.open(db_filepath, "w")
    if not file then return false end

    file:write("-- Auto-generated by FV_TrackFlow\nreturn {\n")
    for _, item in ipairs(Core.track_templates) do
        file:write("  {\n")
        file:write("    id = \"" .. item.id .. "\",\n")
        file:write("    display_name = \"" .. item.display_name .. "\",\n")
        local safe_path = string.gsub(item.file_path, "\\", "/")
        file:write("    file_path = \"" .. safe_path .. "\",\n")
        file:write("    target_folder = \"" .. (item.target_folder or "") .. "\",\n")
        
        file:write("    tree_path = {")
        if item.tree_path then
            for i, p in ipairs(item.tree_path) do file:write("\"" .. p .. "\"" .. (i < #item.tree_path and ", " or "")) end
        end
        file:write("},\n")
        
        file:write("    tags = {")
        if item.tags then
            for i, t in ipairs(item.tags) do file:write("\"" .. string.upper(t) .. "\"" .. (i < #item.tags and ", " or "")) end
        end
        file:write("},\n")
        
        file:write("    routing = {\n      sends = {\n")
        if item.routing and item.routing.sends then
            for _, send in ipairs(item.routing.sends) do
                if send.target and send.target ~= "" then
                    file:write("        { target = \"" .. send.target .. "\", level_db = " .. tostring(send.level_db) .. " },\n")
                end
            end
        end
        file:write("      }\n    }\n  },\n")
    end
    file:write("}\n")
    file:close()
    return true
end

-- YENI: Arayuzdeki Auto-complete (Tamamlama) icin tum tagleri listeler
function Core.GetAllTags()
    local tags_map = {}
    for t, _ in pairs(Core.tag_configs) do tags_map[string.upper(t)] = true end
    for _, item in ipairs(Core.track_templates) do
        if item.tags then
            for _, t in ipairs(item.tags) do tags_map[string.upper(t)] = true end
        end
    end
    local tags_list = {}
    for t, _ in pairs(tags_map) do table.insert(tags_list, t) end
    table.sort(tags_list)
    return tags_list
end

function Core.UpdateCache(search_text, nav_path)
    local current_view = {}
    local folder_seen = {}

    -- YENI: Arama metnini kelimelere (bosluklara gore) boluyoruz
    local search_words = {}
    if search_text ~= "" then
        for w in string.gmatch(string.lower(search_text), "%S+") do table.insert(search_words, w) end
    end

    for _, item in ipairs(Core.track_templates) do
        if item.file_path ~= "" then
            if #search_words > 0 then
                -- YENI: Coklu kelime (AND) mantigi. Track tum kelimeleri barindirmali.
                local all_match = true
                local match_score = 0
                
                for _, word in ipairs(search_words) do
                    local word_match = false
                    local folder_path = item.tree_path and table.concat(item.tree_path, " / ") or ""
                    
                    if string.find(string.lower(folder_path), word, 1, true) then word_match = true; match_score = match_score + 1
                    elseif string.find(string.lower(item.display_name), word, 1, true) then word_match = true; match_score = match_score + 2
                    elseif item.tags then
                        for _, t in ipairs(item.tags) do
                            if string.find(string.lower(t), word, 1, true) then word_match = true; match_score = match_score + 3; break end
                        end
                    end
                    
                    if not word_match then all_match = false; break end
                end
                
                if all_match then 
                    item.search_score = match_score 
                    table.insert(current_view, { type = "item", data = item }) 
                end
            else
                local match_path = true
                for i = 1, #nav_path do
                    if not item.tree_path or item.tree_path[i] ~= nav_path[i] then match_path = false break end
                end
                
                if match_path then
                    local item_depth = item.tree_path and #item.tree_path or 0
                    local nav_depth = #nav_path
                    
                    if item_depth == nav_depth then
                        table.insert(current_view, { type = "item", data = item })
                    elseif item_depth > nav_depth then
                        local folder_name = item.tree_path[nav_depth + 1]
                        if not folder_seen[folder_name] then
                            folder_seen[folder_name] = true
                            table.insert(current_view, { type = "folder", name = folder_name })
                        end
                    end
                end
            end
        end
    end

    if search_text ~= "" then
        table.sort(current_view, function(a, b)
            if a.data.search_score == b.data.search_score then return a.data.display_name:lower() < b.data.display_name:lower() end
            return a.data.search_score > b.data.search_score
        end)
    end
    
    return current_view
end

function Core.InsertTrackTemplateList(items, block_name, is_drag_drop)
    if not items or #items == 0 then return false end

    local valid_items = {}
    local has_missing = false

    for i = 1, #items do
        local item = items[i]
        local template_path = item.file_path
        if not (string.match(template_path, "^[a-zA-Z]:") or string.match(template_path, "^/")) then
            template_path = reaper.GetResourcePath() .. "/TrackTemplates/" .. template_path
        end

        if reaper.file_exists(template_path) then
            item.is_missing = false
            table.insert(valid_items, item)
        else
            item.is_missing = true
            has_missing = true
        end
    end

    if #valid_items == 0 then return has_missing end

    reaper.Undo_BeginBlock()
    reaper.PreventUIRefresh(1)

    local base_sel_track = reaper.GetSelectedTrack(0, 0)
    local global_close_amount = 0
    local global_close_track = nil

    if base_sel_track then
        local d = reaper.GetMediaTrackInfo_Value(base_sel_track, "I_FOLDERDEPTH")
        if d < 0 then
            global_close_amount = d
            reaper.SetMediaTrackInfo_Value(base_sel_track, "I_FOLDERDEPTH", 0)
        end
    end

    local last_inserted_for_target = {}
    local target_folders_to_close = {} 
    local last_inserted_global = nil

    for i = 1, #valid_items do
        local item = valid_items[i]
        local template_path = item.file_path
        if not (string.match(template_path, "^[a-zA-Z]:") or string.match(template_path, "^/")) then
            template_path = reaper.GetResourcePath() .. "/TrackTemplates/" .. template_path
        end

        local target_found = false
        local target_name_lower = ""

        if not is_drag_drop and item.target_folder and item.target_folder ~= "" then
            target_name_lower = string.lower(item.target_folder)

            if last_inserted_for_target[target_name_lower] and reaper.ValidatePtr(last_inserted_for_target[target_name_lower], "MediaTrack*") then
                reaper.SetOnlyTrackSelected(last_inserted_for_target[target_name_lower])
                target_found = true
            else
                for j = 0, reaper.CountTracks(0) - 1 do
                    local t = reaper.GetTrack(0, j)
                    local _, t_name = reaper.GetSetMediaTrackInfo_String(t, "P_NAME", "", false)
                    if string.lower(t_name) == target_name_lower then
                        reaper.SetOnlyTrackSelected(t)
                        target_found = true
                        local depth = reaper.GetMediaTrackInfo_Value(t, "I_FOLDERDEPTH")
                        if depth <= 0 then
                            reaper.SetMediaTrackInfo_Value(t, "I_FOLDERDEPTH", 1)
                            target_folders_to_close[target_name_lower] = { track = nil, amount = depth - 1 }
                        end
                        break
                    end
                end
            end
        end

        if not target_found then
            if last_inserted_global and reaper.ValidatePtr(last_inserted_global, "MediaTrack*") then
                reaper.SetOnlyTrackSelected(last_inserted_global)
            elseif base_sel_track and reaper.ValidatePtr(base_sel_track, "MediaTrack*") then
                reaper.SetOnlyTrackSelected(base_sel_track)
            else
                reaper.Main_OnCommand(40297, 0)
            end
        end

        reaper.Main_openProject(template_path)
        local num_selected = reaper.CountSelectedTracks(0)
        
        if num_selected > 0 then
            local last_new_track = reaper.GetSelectedTrack(0, num_selected - 1)
            
            if target_found then
                last_inserted_for_target[target_name_lower] = last_new_track
                if target_folders_to_close[target_name_lower] then
                    target_folders_to_close[target_name_lower].track = last_new_track
                end
            else
                last_inserted_global = last_new_track
                global_close_track = last_new_track
            end

            if item.routing and item.routing.sends then
                for k = 0, num_selected - 1 do
                    local new_track = reaper.GetSelectedTrack(0, k)
                    for _, send_data in ipairs(item.routing.sends) do
                        local fx_track = nil
                        for j = 0, reaper.CountTracks(0) - 1 do
                            local t = reaper.GetTrack(0, j)
                            local _, t_name = reaper.GetSetMediaTrackInfo_String(t, "P_NAME", "", false)
                            if t_name == send_data.target then fx_track = t break end
                        end
                        if fx_track then
                            local send_idx = reaper.CreateTrackSend(new_track, fx_track)
                            local level_val = 10 ^ ((send_data.level_db or 0) / 20)
                            reaper.SetTrackSendInfo_Value(new_track, 0, send_idx, "D_VOL", level_val)
                        end
                    end
                end
            end
        end
    end

    for _, data in pairs(target_folders_to_close) do
        if data.track and reaper.ValidatePtr(data.track, "MediaTrack*") then
            local d = reaper.GetMediaTrackInfo_Value(data.track, "I_FOLDERDEPTH")
            reaper.SetMediaTrackInfo_Value(data.track, "I_FOLDERDEPTH", d + data.amount)
        end
    end

    if global_close_track and global_close_amount < 0 then
        if reaper.ValidatePtr(global_close_track, "MediaTrack*") then
            local d = reaper.GetMediaTrackInfo_Value(global_close_track, "I_FOLDERDEPTH")
            reaper.SetMediaTrackInfo_Value(global_close_track, "I_FOLDERDEPTH", d + global_close_amount)
        end
    elseif not global_close_track and base_sel_track and global_close_amount < 0 then
        if reaper.ValidatePtr(base_sel_track, "MediaTrack*") then
            local d = reaper.GetMediaTrackInfo_Value(base_sel_track, "I_FOLDERDEPTH")
            reaper.SetMediaTrackInfo_Value(base_sel_track, "I_FOLDERDEPTH", d + global_close_amount)
        end
    end

    reaper.PreventUIRefresh(-1)
    reaper.TrackList_AdjustWindows(false)
    reaper.UpdateArrange()
    reaper.Undo_EndBlock(block_name or "Insert Multiple Templates", -1)
    
    return has_missing
end

function Core.InsertTrackTemplate(item, is_drag_drop)
    return Core.InsertTrackTemplateList({item}, "Insert Track Template: " .. item.display_name, is_drag_drop)
end

function Core.GetTagColor(tag)
    local t = string.upper(tag)
    if Core.tag_configs[t] and Core.tag_configs[t].color then return Core.tag_configs[t].color end
    return 0x9E9E9EFF
end

function Core.GetTagShortName(tag)
    local t = string.upper(tag)
    if Core.tag_configs[t] and Core.tag_configs[t].short then return Core.tag_configs[t].short end
    return string.sub(t, 1, 3)
end

return Core